# Generated by Django 4.2.10 on 2024-02-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0003_alter_insight_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
