# Generated by Django 4.2.10 on 2024-02-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0004_alter_insight_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='url',
            field=models.URLField(max_length=2000),
        ),
    ]
