# Generated by Django 4.2.10 on 2024-02-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0007_alter_insight_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='country',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='insight',
            name='pestle',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='insight',
            name='region',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='insight',
            name='source',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
