# Generated by Django 4.2.10 on 2024-02-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0008_alter_insight_country_alter_insight_pestle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='pestle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='insight',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
