# Generated by Django 4.2.10 on 2024-02-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0010_alter_insight_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='source',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
