# Generated by Django 4.2.10 on 2024-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0011_alter_insight_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='end_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
