# Generated by Django 4.2.10 on 2024-02-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0013_alter_insight_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='impact',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
