# Generated by Django 4.2.10 on 2024-02-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0016_alter_insight_country_alter_insight_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
