# Generated by Django 4.2.10 on 2024-02-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_app', '0018_alter_insight_end_year_alter_insight_intensity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='likelihood',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='pestle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='source',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='insight',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
